spring:
  application:
    name: question-service

  datasource:
    url: jdbc:postgresql://localhost:5433/question_db
    username: question_user
    password: question_pass

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8082

logging:
  level:
    liquibase: INFO
    liquibase.executor: INFO
    liquibase.changelog: INFO